### ISSUE TITLE
HyperTensioN configuration

### ISSUE THREAD

**Issue by Maumagnaguagno** [NikolaiLMS/mastersthesis-experimental-data#1]
Hello, I am the author of HyperTensioN, the planner you compared against.
I found odd that no Entertainment instances were solved in your tests, as I remember fixing a parsing bug after the IPC that made the first 5 instances easily solvable (less than a second) in an old machine, repeated the tests today and they remain solvable.

Upon inspection I noticed that you are using a newer version (based on the hash in the folder name) but not the same configuration used during the IPC.
The commands from [runwatch_commands.txt](https://github.com/NikolaiLMS/mastersthesis-experimental-data/blob/main/evaluations/sotaevaluation/Hypertension_4169727dc9cfd/runwatch_commands.txt) lack the preprocessing stages triggered by parameters provided to Hype.
HyperTensioN was deployed in the IPC with ``ruby Hype.rb <domain.hddl> <problem.hddl> typredicate pullup dejavu run``, and it appears you applied just ``run``, which is the same as unoptimized.
You can see more about it [here](https://github.com/Maumagnaguagno/HyperTensioN/blob/master/docs/IPC.md).

This is probably the main reason for your comment in 4.5.1: *the difference for the named planners performance should still be noted and possibly investigated in future work.*

I also find it odd that you have rigid/fluent precondition preprocessing stages to prune possible paths and never compared to HyperTensioN's Pullup approach.
Elements from [Fact analysis](https://github.com/NikolaiLMS/lilotane/blob/master/src/algo/fact_analysis.cpp#L99-L112) are far too similar to [Pullup](https://github.com/Maumagnaguagno/HyperTensioN/blob/master/extensions/Pullup.rb#L19-L38) from my perspective.

Also, Lavindra's name is all caps in your Thesis bibliography [16].

**Comment by domschrei** [comment]
Hi there! Just a few words from my point of view (the supervisor of this thesis). 
Thanks for the valuable feedback! It's great that you found the time to look that closely at @NikolaiLMS 's work.

>Elements from Fact analysis are far too similar to Pullup from my perspective.

Essentially, we took Lilotane as a point of origin, generalized its "precondition inference" code, which is similar to HyperTensioN's "pullup" of preconditions (as acknowledged earlier by Lilotane's journal article), and then looked what could be improved. As you pointed out, in some aspects we (again) arrived at similar techniques to what HyperTensioN does, perhaps due to our similar points of departure, but we were not aware of this. So please be assured that @NikolaiLMS or myself did not take any ideas or inspirations from HyperTensioN for this work. That being said, in case we actually publish this work in the future, we'll make sure to reference your approach and point out the similarities, so thanks again for this remark.

As a side note, is there already a publication on these techniques of HyperTensioN's (apart from the IPC description)?

**Comment by Maumagnaguagno** [comment]
I understand that @NikolaiLMS reached a similar solution on his own, it was just odd that no comparison with Pullup appears in the text, while the IPC paper is cited and no optimizations (including Pullup) appear in the runwatch file.
Unfortunately there is only the IPC paper for now, once I finish testing a new idea I will start working on a paper/journal.

**Comment by domschrei** [comment]
I see. HyperTensioN is "only" cited due to its inclusion in the experiments (and due to its good HTN performance overall), not because we looked into its techniques.

Running HyperTensioN unoptimized was an error in the setup. Maybe it would be worthwhile to make this the default configuration of HyperTensioN when simply cloning and running it?

>once I finish testing a new idea I will start working on a paper/journal.

Sounds good! This will make the techniques in HyperTensioN more visible for future works.

**Comment by Maumagnaguagno** [comment]
> Running HyperTensioN unoptimized was an error in the setup. Maybe it would be worthwhile to make this the default configuration of HyperTensioN when simply cloning and running it?

The problem is that I don't expect everyone to use it the same way, as some parts result in analysis output, [conversion between planning descriptions](https://icaps17.icaps-conference.org/workshops/KEPS/proceedingsKEPS.pdf#page=57), some optimizations may be too costly, or even require a C++ compiler to execute the planner natively.
I will try to improve my README to make it easier for others to compare against HyperTensioN.

I just wanted to know if the results were obtained with that runwatch file, which you just confirmed, otherwise there was a bug in the optimizations.
Could one of you add a note in the README about how you executed each planner and that HyperTensioN does not include the IPC optimizations?
My fear is that someone else clones this repo and repeats the mistake.
You should also contact the developers of PandaGBFS about this, could be the same thing.

**Comment by NikolaiLMS** [comment]
Hello! Thank you for your feedback and sorry for the delay. I have now added a [section](https://github.com/NikolaiLMS/mastersthesis-experimental-data/blob/main/README.md#execution-of-planners) in the README as requested.

**Comment by Maumagnaguagno** [comment]
Thanks, I am in the process of improving/rewriting my own README too.
I guess that solves it, I am closing this issue.
